export default {
    name: "Atal Innovation Mission",
    baseUrl: "https://aim.gov.in/",
    startUrls: [
        "https://aim.gov.in/",
        "https://aim.gov.in/atl.php",
        "https://aim.gov.in/aic.php",
        "https://aim.gov.in/acic.php",
        "https://aim.gov.in/arise.php",
        "https://aim.gov.in/aim-i2e.php"
    ],
    allowedDomains: [
        "aim.gov.in",
        "www.aim.gov.in"
    ],
    includePatterns: [
        "scheme",
        "policy",
        "guideline",
        "startup",
        "fund",
        "finance",
        "loan",
        "subsidy",
        "blog",
        "article",
        "challenge",
        "initiative",
        "notification",
        "circular",
        "faq",
        "resource",
        "report",
        "publication",
        "offering",
        "incentive",
        "opportunity",
        "atl",
        "aic",
        "acic",
        "arise"
    ],
    excludePatterns: [
        "login",
        "logout",
        "register",
        "signup",
        "dashboard",
        "profile",
        "notification-settings",
        "settings",
        "password",
        "privacy",
        "terms",
        "sitemap",
        "feedback",
        "contact",
        "subscribe",
        "search",
        "verify",
        "certificate",
        "download-certificate",
        "otp",
        "digilocker",
        "create-password",
        "reset-password",
        "account",
        "modal",
        "popup",
        "grievance",
        "careers",
        "tenders"
    ],
    followLinks: true,
    maxDepth: 3,
    crawlFrequency: "weekly",
    tags: [
        "startup",
        "government",
        "india",
        "niti-aayog",
        "aim",
        "atal-innovation-mission",
        "incubator",
        "funding",
        "grant",
        "scheme",
        "innovation"
    ]
};
