export default {
    name: "DPIIT",
    baseUrl: "https://www.dpiit.gov.in",
    startUrls: [
        "https://www.dpiit.gov.in/",
        "https://www.dpiit.gov.in/offerings",
        "https://www.dpiit.gov.in/offerings/initiative",
        "https://www.dpiit.gov.in/offerings/initiative/details/startup-india-initiative-and-related-schemes-1gTM1ETMtQWa",
        "https://www.dpiit.gov.in/documents",
        "https://www.dpiit.gov.in/whats-new",
        "https://www.dpiit.gov.in/important-links"
    ],
    allowedDomains: [
        "dpiit.gov.in",
        "www.dpiit.gov.in"
    ],
    includePatterns: [
        "scheme",
        "policy",
        "guideline",
        "startup",
        "fund",
        "finance",
        "loan",
        "subsidy",
        "blog",
        "article",
        "challenge",
        "initiative",
        "notification",
        "circular",
        "faq",
        "resource",
        "report",
        "publication",
        "offering",
        "incentive",
        "opportunity",
        "details",
        "documents",
        "whats-new",
        "important-links"
    ],
    excludePatterns: [
        "login",
        "logout",
        "register",
        "signup",
        "dashboard",
        "profile",
        "notification-settings",
        "settings",
        "password",
        "privacy",
        "terms",
        "sitemap",
        "feedback",
        "contact",
        "subscribe",
        "search",
        "verify",
        "certificate",
        "download-certificate",
        "otp",
        "digilocker",
        "create-password",
        "reset-password",
        "account",
        "modal",
        "popup",
        "grievance",
        "careers",
        "tenders"
    ],
    followLinks: true,
    maxDepth: 3,
    crawlFrequency: "weekly",
    tags: [
        "startup",
        "government",
        "india",
        "dpiit",
        "funding",
        "seed-fund",
        "credit-guarantee",
        "tax-exemption",
        "startup-recognition",
        "industrial-policy",
        "investment-promotion",
        "gazette-notification",
        "scheme"
    ]
}