export default {
    name: "GeM_GovernmentEMarketplace",
    baseUrl: "https://gem.gov.in",
    startUrls: [
        "https://gem.gov.in/Startup_Runway",
        "https://gem.gov.in/business-opportunities",
        "https://gem.gov.in/support/government_oms_circulars",
        "https://gem.gov.in/support/buyers",
        "https://gem.gov.in/userFaqs",
        "https://gem.gov.in/gem_hand_book"
    ],
    allowedDomains: [
        "gem.gov.in",
        "www.gem.gov.in"
    ],
    includePatterns: [
        "scheme",
        "policy",
        "guideline",
        "startup",
        "fund",
        "finance",
        "loan",
        "subsidy",
        "blog",
        "article",
        "challenge",
        "initiative",
        "notification",
        "circular",
        "faq",
        "resource",
        "report",
        "publication",
        "offering",
        "incentive",
        "opportunity",
        "runway"
    ],
    excludePatterns: [
        "login",
        "logout",
        "register",
        "signup",
        "dashboard",
        "profile",
        "notification-settings",
        "settings",
        "password",
        "privacy",
        "terms",
        "sitemap",
        "feedback",
        "contact",
        "subscribe",
        "search",
        "verify",
        "certificate",
        "download-certificate",
        "otp",
        "digilocker",
        "create-password",
        "reset-password",
        "account",
        "modal",
        "popup",
        "grievance",
        "careers",
        "tenders"
    ],
    followLinks: true,
    maxDepth: 3,
    crawlFrequency: "weekly",
    tags: [
        "gem",
        "government",
        "india",
        "procurement",
        "public-procurement",
        "startup-runway",
        "business-opportunity",
        "circular"
    ]
}