export default {
    name: "invest-india",
    baseUrl: "https://www.investindia.gov.in",
    startUrls: [
        "https://www.investindia.gov.in/india-opportunity",
        "https://www.investindia.gov.in/schemes-incentives",
        "https://www.investindia.gov.in/national-single-window-system"
    ],
    allowedDomains: [
        "investindia.gov.in",
        "www.investindia.gov.in"
    ],
    includePatterns: [
        "scheme",
        "policy",
        "guideline",
        "startup",
        "fund",
        "finance",
        "loan",
        "subsidy",
        "blog",
        "article",
        "challenge",
        "initiative",
        "notification",
        "circular",
        "faq",
        "resource",
        "report",
        "publication",
        "offering",
        "incentive",
        "opportunity"
    ],
    excludePatterns: [
        "login",
        "logout",
        "register",
        "signup",
        "dashboard",
        "profile",
        "notification-settings",
        "settings",
        "password",
        "privacy",
        "terms",
        "sitemap",
        "feedback",
        "contact",
        "subscribe",
        "search",
        "verify",
        "certificate",
        "download-certificate",
        "otp",
        "digilocker",
        "create-password",
        "reset-password",
        "account",
        "modal",
        "popup",
        "grievance",
        "careers",
        "tenders"
    ],
    followLinks: true,
    maxDepth: 3,
    crawlFrequency: "weekly",
    tags: [
        "invest-india",
        "government",
        "india",
        "investment",
        "incentives",
        "schemes",
        "policy",
        "fdi"
    ]
}