export default {
    name: "MeitY Startup Hub",
    baseUrl: "https://msh.meity.gov.in/",
    startUrls: [
        "https://msh.meity.gov.in/",
        "https://msh.meity.gov.in/schemes/samridh",
        "https://msh.meity.gov.in/schemes/sasact"
    ],
    allowedDomains: [
        "msh.meity.gov.in",
        "meity.gov.in",
        "dic.gov.in"
    ],
    includePatterns: [
        "scheme",
        "policy",
        "guideline",
        "startup",
        "fund",
        "finance",
        "loan",
        "subsidy",
        "blog",
        "article",
        "challenge",
        "initiative",
        "notification",
        "circular",
        "faq",
        "resource",
        "report",
        "publication",
        "offering",
        "incentive",
        "opportunity",
        "samridh",
        "sasact",
        "schemes"
    ],
    excludePatterns: [
        "login",
        "logout",
        "register",
        "signup",
        "dashboard",
        "profile",
        "notification-settings",
        "settings",
        "password",
        "privacy",
        "terms",
        "sitemap",
        "feedback",
        "contact",
        "subscribe",
        "search",
        "verify",
        "certificate",
        "download-certificate",
        "otp",
        "digilocker",
        "create-password",
        "reset-password",
        "account",
        "modal",
        "popup",
        "grievance",
        "careers",
        "tenders"
    ],
    followLinks: true,
    maxDepth: 3,
    crawlFrequency: "weekly",
    tags: [
        "startup",
        "government",
        "india",
        "meity",
        "funding",
        "grant",
        "incubator",
        "accelerator",
        "scheme",
        "deeptech",
        "policy"
    ]
}