export default {
    name: "MSME",
    baseUrl: "https://www.msme.gov.in",
    startUrls: [
        "https://www.msme.gov.in/offerings",
        "https://www.msme.gov.in/all-schemes",
        "https://www.msme.gov.in/faqs"
    ],
    allowedDomains: [
        "msme.gov.in",
        "www.msme.gov.in",
        "my.msme.gov.in",
        "champions.gov.in"
    ],
    includePatterns: [
        "scheme",
        "policy",
        "guideline",
        "startup",
        "fund",
        "finance",
        "loan",
        "subsidy",
        "blog",
        "article",
        "challenge",
        "initiative",
        "notification",
        "circular",
        "faq",
        "resource",
        "report",
        "publication",
        "offering",
        "incentive",
        "opportunity",
        "node",
        "details",
        "document",
        "page",
        "content"
    ],
    excludePatterns: [
        "login",
        "logout",
        "register",
        "signup",
        "dashboard",
        "profile",
        "notification-settings",
        "settings",
        "password",
        "privacy",
        "terms",
        "sitemap",
        "feedback",
        "contact",
        "subscribe",
        "search",
        "verify",
        "certificate",
        "download-certificate",
        "otp",
        "digilocker",
        "create-password",
        "reset-password",
        "account",
        "modal",
        "popup",
        "grievance",
        "careers",
        "tenders"
    ],
    followLinks: true,
    maxDepth: 3,
    crawlFrequency: "weekly",
    tags: [
        "msme",
        "government",
        "india",
        "funding",
        "subsidy",
        "credit-guarantee",
        "cluster-development",
        "technology-upgradation",
        "scheme"
    ]
}