export default {
    name: "NSWS - National Single Window System",
    baseUrl: "https://www.nsws.gov.in",
    startUrls: [
        "https://www.nsws.gov.in/about-us",
        "https://www.nsws.gov.in/portal/scheme/pli-scheme",
        "https://www.nsws.gov.in/portal/user-guide"
    ],
    allowedDomains: [
        "nsws.gov.in",
        "www.nsws.gov.in",
        "nodal-authority.nsws.gov.in"
    ],
    includePatterns: [
        "scheme",
        "policy",
        "guideline",
        "startup",
        "fund",
        "finance",
        "loan",
        "subsidy",
        "blog",
        "article",
        "challenge",
        "initiative",
        "notification",
        "circular",
        "faq",
        "resource",
        "report",
        "publication",
        "offering",
        "incentive",
        "opportunity",
        "guide",
        "approval"
    ],
    excludePatterns: [
        "login",
        "logout",
        "register",
        "signup",
        "dashboard",
        "profile",
        "notification-settings",
        "settings",
        "password",
        "privacy",
        "terms",
        "sitemap",
        "feedback",
        "contact",
        "subscribe",
        "search",
        "verify",
        "certificate",
        "download-certificate",
        "otp",
        "digilocker",
        "create-password",
        "reset-password",
        "account",
        "modal",
        "popup",
        "grievance",
        "careers",
        "tenders"
    ],
    followLinks: true,
    maxDepth: 3,
    crawlFrequency: "weekly",
    tags: [
        "nsws",
        "government",
        "india",
        "single-window",
        "approvals",
        "pli-scheme",
        "licenses",
        "clearances"
    ]
}