export default {
    name: "SIDBI",
    baseUrl: "https://www.sidbi.in/",
    startUrls: [
        "https://www.sidbi.in/en/home-product",
        "https://www.sidbi.in/en/products-and-services",
        "https://www.sidbi.in/en/schemes-initiatives",
        "https://www.sidbi.in/en/venture-capital-funds-of-funds"
    ],
    allowedDomains: [
        "sidbi.in",
        "www.sidbi.in"
    ],
    includePatterns: [
        "scheme",
        "policy",
        "guideline",
        "startup",
        "fund",
        "finance",
        "loan",
        "subsidy",
        "blog",
        "article",
        "challenge",
        "initiative",
        "notification",
        "circular",
        "faq",
        "resource",
        "report",
        "publication",
        "offering",
        "incentive",
        "opportunity"
    ],
    excludePatterns: [
        "login",
        "logout",
        "register",
        "signup",
        "dashboard",
        "profile",
        "notification-settings",
        "settings",
        "password",
        "privacy",
        "terms",
        "sitemap",
        "feedback",
        "contact",
        "subscribe",
        "search",
        "verify",
        "certificate",
        "download-certificate",
        "otp",
        "digilocker",
        "create-password",
        "reset-password",
        "account",
        "modal",
        "popup",
        "grievance",
        "careers",
        "tenders"
    ],
    followLinks: true,
    maxDepth: 3,
    crawlFrequency: "weekly",
    tags: [
        "sidbi",
        "government",
        "india",
        "funding",
        "venture-capital",
        "fund-of-funds",
        "direct-lending",
        "msme-finance",
        "scheme"
    ]
}