export default {
    name: "StartupIndia",
    baseUrl: "https://www.startupindia.gov.in/",
    startUrls: [
        "https://www.startupindia.gov.in/content/sih/en/startup-scheme.html",
        "https://www.startupindia.gov.in/content/sih/en/startupgov/startup_recognition_page.html",
        "https://www.startupindia.gov.in/content/sih/en/startupgov/regulatory_updates.html",
        "https://www.startupindia.gov.in/content/sih/en/startupgov/imb.html",
        "https://www.startupindia.gov.in/content/sih/en/startupgov/self-certification.html",
        "https://www.startupindia.gov.in/content/sih/en/government-schemes.html",
        "https://www.startupindia.gov.in/content/sih/en/incubator-schemes.html",
        "https://www.startupindia.gov.in/content/sih/en/state-startup-policies.html",
        "https://www.startupindia.gov.in/content/sih/en/women_entrepreneurs.html",
        "https://www.startupindia.gov.in/content/sih/en/credit-guarantee-scheme-for-startups.html",
        "https://www.startupindia.gov.in/content/sih/en/public_procurement.html",
        "https://www.startupindia.gov.in/content/sih/en/intellectual-property-rights.html",
        "https://www.startupindia.gov.in/content/sih/en/about_us/faqs.html",
        "https://seedfund.startupindia.gov.in/",
        "https://investorconnect.startupindia.gov.in/"
    ],
    allowedDomains: [
        "startupindia.gov.in",
        "www.startupindia.gov.in",
        "seedfund.startupindia.gov.in",
        "investorconnect.startupindia.gov.in",
        "maarg.startupindia.gov.in"
    ],
    includePatterns: [
        "scheme",
        "policy",
        "guideline",
        "startup",
        "fund",
        "finance",
        "loan",
        "subsidy",
        "blog",
        "article",
        "challenge",
        "initiative",
        "notification",
        "circular",
        "faq",
        "resource",
        "report",
        "publication",
        "offering",
        "incentive",
        "opportunity"
    ],
    excludePatterns: [
        "login",
        "logout",
        "register",
        "signup",
        "dashboard",
        "profile",
        "notification-settings",
        "settings",
        "password",
        "privacy",
        "terms",
        "sitemap",
        "feedback",
        "contact",
        "subscribe",
        "search",
        "verify",
        "certificate",
        "download-certificate",
        "otp",
        "digilocker",
        "create-password",
        "reset-password",
        "account",
        "modal",
        "popup",
        "grievance",
        "careers",
        "tenders"
    ],
    followLinks: true,
    maxDepth: 3,
    crawlFrequency: "weekly",
    tags: [
        "startup",
        "government",
        "india",
        "dpiit",
        "funding",
        "seed-fund",
        "grant",
        "incubator",
        "policy",
        "scheme",
        "tax-exemption",
        "recognition",
        "compliance",
        "state-policy",
        "investor"
    ]
}